version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: portainer_web_1
      APP_PORT: 9000

  web:
    image: portainer/portainer-ce:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#    environment:
#      BTCEXP_PORT: 8080
